### ISSUE TITLE
License issue

### ISSUE THREAD

**Issue by muhammd2** [XRSec/AWVS-Update#11]
asking for license key, please take a look

**Comment by muhammd2** [comment]
it used to be activated in the past, but now each time when logging in, it ask for license key

**Comment by Ran-Xing** [comment]
<img width="700" alt="image" src="https://github.com/XRSec/AWVS-Update/assets/73819467/a1c4ad24-cc86-44dd-afdd-ef8e6ef63ad4">
<img width="702" alt="image" src="https://github.com/XRSec/AWVS-Update/assets/73819467/96cc0f3f-26c3-4a94-b890-4dd5ea2461db">

**Comment by Ran-Xing** [comment]
@muhammd2

**Comment by SantiEich** [comment]
Any workaround? 

<img width="1492" alt="image" src="https://github.com/XRSec/AWVS-Update/assets/21198777/379d456a-c7d8-4872-854a-bb5fab90d38e">

**Comment by jesussuarz** [comment]
> Any workaround?
> 

Hello, please see my solution. Maybe this is the same problem.

https://github.com/jesussuarz/Acunetix_Full_awvs_23.x
