### ISSUE TITLE
AWVS错误

### ISSUE THREAD

**Issue by mac3d0** [XRSec/AWVS-Update#12]
安装成功。但是，当我运行扫描程序时，该工具没有显示列出的漏洞。数据库肯定有问题。你能帮助我吗？

![Screenshot_2024-05-29_15-26-11](https://github.com/XRSec/AWVS-Update/assets/43928011/9d495003-34ab-491d-ad36-878dcb0f6264)

**Comment by Ran-Xing** [comment]
@mac3d0 You can ask questions here：https://t.me/pwn3rzs_chat  but this is not my group, I recently updated AWVS to a new version, and there is no complete test. If you have any new findings, please feedback here. and you can use the following for related errors: docker logs -f awvs

**Comment by Ran-Xing** [comment]
@mac3d0 https://github.com/jesussuarz/Acunetix_Full_awvs_23.x this repo is very good!

**Comment by mac3d0** [comment]
@Ran-Xing The bad thing is that I already tried the repository and the same thing happened, to tell the truth the same error of not cataloging the vulnerabilities happens in all the versions I install.

**Comment by mac3d0** [comment]
[logs_awvs.txt](https://github.com/XRSec/AWVS-Update/files/15490773/logs_awvs.txt)

@Ran-Xing Please take a look at my records and see if there is anything wrong.

**Comment by akoasmking** [comment]
在安装完成之后，一打开 就出现这个错误：：An error occurredUnauthorizedRefresh the page
![awvs](https://github.com/user-attachments/assets/eafaf9e6-4289-43af-9e4a-d36c5b6298a5)

**Comment by Ran-Xing** [comment]
@akoasmking clean cookies

**Comment by akoasmking** [comment]
> @akoasmking clean cookies

Thank you so much, the problem has been resolved
