### ISSUE TITLE
docker AWVS  出错

### ISSUE THREAD

**Issue by abandon0326** [XRSec/AWVS-Update#2]
你好,
我参照这您在hub.docker.com的说明使用docker pull xrsec/awvs  拉取镜像

docker run -it -d \
--name awvs \
-p 3443:3443 \
--restart=always \
ghcr.io/xrsec/awvs:latest

但是安装后访问端口3443 出现无法访问。我确认我的防火墙是关闭的 开放了所有端口，这似乎好像是一个通病  其他的awvs的docker 安装运行后 访问ip+端口 都是无法访问的情况 并没有出现登录页面。 
http://ip+port 
https://ip+pott
都常识过  但都是失败的

服务器  物理机 也都尝试过2  但都无法解决
期待您的回答。

**Comment by XRSec** [comment]
你可以给我发邮件嘛？

**Comment by Ran-Xing** [comment]
@luckfoxer 你可以给我发邮件嘛？

**Comment by jesussuarz** [comment]
> 你好, 我参照这您在hub.docker.com的说明使用docker pull xrsec/awvs 拉取镜像
> 
> docker run -it -d --name awvs -p 3443:3443 --restart=always ghcr.io/xrsec/awvs:latest
> 
> 但是安装后访问端口3443 出现无法访问。我确认我的防火墙是关闭的 开放了所有端口，这似乎好像是一个通病 其他的awvs的docker 安装运行后 访问ip+端口 都是无法访问的情况 并没有出现登录页面。 http://ip+port https://ip+pott 都常识过 但都是失败的
> 
> 服务器 物理机 也都尝试过2 但都无法解决 期待您的回答。

Start with https://localhost:3443
