### ISSUE TITLE
大佬，安装之后是要求输入激活许可证的

### ISSUE THREAD

**Issue by 98Kstar** [XRSec/AWVS-Update#3]
![image](https://user-images.githubusercontent.com/41816999/146110910-a2337566-606b-40c3-9df3-cd558dbab953.png)

**Comment by abandon0326** [comment]
你也在docker装吗，为什么我docker安装后 页面都打不开 就很奇怪

**Comment by Ran-Xing** [comment]
@98Kstar 由于破解有风险，所以你可以看看别人的破解，比如fahai.org

**Comment by Ran-Xing** [comment]
请通过正版授权激活，临时使用可以参考下fahai.org，支持正版，人人有责！

**Comment by evil0x-c** [comment]
他这个破解方法想要一直用，必须把license设置为只读，不然会被awvs修改回未授权，而且这个破解法我实验了下，没办法手动录制脚本，高级功能用不了

**Comment by Ran-Xing** [comment]
@evil0x-c 你去她博客看看第一篇文章

**Comment by evil0x-c** [comment]
> @evil0x-c 你去她博客看看第一篇文章

文章需要权限，不过我大概知道怎么回事wvsc.exe这个文件需要替换

**Comment by 18852002209** [comment]
<img width="594" alt="图片" src="https://user-images.githubusercontent.com/48916008/185543915-8f402d26-86dd-4aa0-bdf0-922a3b56064c.png">

大佬扫描失败怎么回事呀

**Comment by TrojanAZhen** [comment]
dd1

**Comment by Ran-Xing** [comment]
@TrojanAZhen 测试
