### ISSUE TITLE
How Can i Download New Version

### ISSUE THREAD

**Issue by Phoenix1112** [XRSec/AWVS-Update#5]
hello bro. acunetix pro file is shared in many sources. When a new version comes out, it takes some time to hit the market. We can't find a source to download it. so I'm trying to find a way to download the pro file from the acunetix site right after the new version of acunetix pro is released. do you have any idea about it?

**Comment by Ran-Xing** [comment]
I think that's great and helpful, I haven't found the package for a long time @Phoenix1112
