### ISSUE TITLE
来都来了~ 升级一下搞个破解嘛

### ISSUE THREAD

**Issue by ghost** [XRSec/AWVS-Update#6]
来都来了~ 升级一下搞个破解嘛:see_no_evil:
话说现在awvs 14.9 crack好像不能直接在docker ubuntu镜像安装了..
可能是我姿势不对:clown_face:

**Comment by Ran-Xing** [comment]
@Trapshell 哈哈哈，现在这个版本确实有点问题哈哈

**Comment by ghost** [comment]
@Ran-Xing 是啊 这个版本有问题 linux不能安装了

**Comment by Ran-Xing** [comment]
@Trapshell 我不负责破解，爱国守法哦！
