### ISSUE TITLE
Is the latest build working?

### ISSUE THREAD

**Issue by uBadRequest** [XRSec/AWVS-Update#9]
Can't seem to get the latest build/15.3 to activate. Is this what the tag "No Cracking" means?

**Comment by Ran-Xing** [comment]
@uBadRequest We can't get the latest version, it has been updated at present, so enjoy using it!

**Comment by jesussuarz** [comment]
> Can't seem to get the latest build/15.3 to activate. Is this what the tag "No Cracking" means?

Hello, please see my solution. Maybe this is the same problem.

https://github.com/jesussuarz/Acunetix_Full_awvs_23.x
